export const columns = [
  { name: "Flow ID", type: "category" },
  { name: "Src IP", type: "category" },
  { name: "Src Port", type: "int64" },
  { name: "Dst IP", type: "category" },
  { name: "Dst Port", type: "int64" },
  { name: "Protocol", type: "int64" },
  { name: "Timestamp", type: "datetime64[ns]" },
  { name: "Flow Duration", type: "int64" },
  { name: "Total Fwd Packet", type: "int64" },
  { name: "Total Bwd packets", type: "int64" },
  { name: "Total Length of Fwd Packet", type: "int64" },
  { name: "Total Length of Bwd Packet", type: "int64" },
  { name: "Fwd Packet Length Max", type: "int64" },
  { name: "Fwd Packet Length Min", type: "int64" },
  { name: "Fwd Packet Length Mean", type: "float64" },
  { name: "Fwd Packet Length Std", type: "float64" },
  { name: "Bwd Packet Length Max", type: "int64" },
  { name: "Bwd Packet Length Min", type: "int64" },
  { name: "Bwd Packet Length Mean", type: "float64" },
  { name: "Bwd Packet Length Std", type: "float64" },
  { name: "Flow Bytes/s", type: "float64" },
  { name: "Flow Packets/s", type: "float64" },
  { name: "Flow IAT Mean", type: "float64" },
  { name: "Flow IAT Std", type: "float64" },
  { name: "Flow IAT Max", type: "int64" },
  { name: "Flow IAT Min", type: "int64" },
  { name: "Fwd IAT Total", type: "int64" },
  { name: "Fwd IAT Mean", type: "float64" },
  { name: "Fwd IAT Std", type: "float64" },
  { name: "Fwd IAT Max", type: "int64" },
  { name: "Fwd IAT Min", type: "int64" },
  { name: "Bwd IAT Total", type: "int64" },
  { name: "Bwd IAT Mean", type: "float64" },
  { name: "Bwd IAT Std", type: "float64" },
  { name: "Bwd IAT Max", type: "int64" },
  { name: "Bwd IAT Min", type: "int64" },
  { name: "Fwd PSH Flags", type: "int64" },
  { name: "Bwd PSH Flags", type: "int64" },
  { name: "Fwd URG Flags", type: "int64" },
  { name: "Bwd URG Flags", type: "int64" },
  { name: "Fwd RST Flags", type: "int64" },
  { name: "Bwd RST Flags", type: "int64" },
  { name: "Fwd Header Length", type: "int64" },
  { name: "Bwd Header Length", type: "int64" },
  { name: "Fwd Packets/s", type: "float64" },
  { name: "Bwd Packets/s", type: "float64" },
  { name: "Packet Length Min", type: "int64" },
  { name: "Packet Length Max", type: "int64" },
  { name: "Packet Length Mean", type: "float64" },
  { name: "Packet Length Std", type: "float64" },
  { name: "Packet Length Variance", type: "float64" },
  { name: "FIN Flag Count", type: "int64" },
  { name: "SYN Flag Count", type: "int64" },
  { name: "RST Flag Count", type: "int64" },
  { name: "PSH Flag Count", type: "int64" },
  { name: "ACK Flag Count", type: "int64" },
  { name: "URG Flag Count", type: "int64" },
  { name: "CWR Flag Count", type: "int64" },
  { name: "ECE Flag Count", type: "int64" },
  { name: "Down/Up Ratio", type: "float64" },
  { name: "Average Packet Size", type: "float64" },
  { name: "Fwd Segment Size Avg", type: "float64" },
  { name: "Bwd Segment Size Avg", type: "float64" },
  { name: "Fwd Bytes/Bulk Avg", type: "int64" },
  { name: "Fwd Packet/Bulk Avg", type: "int64" },
  { name: "Fwd Bulk Rate Avg", type: "int64" },
  { name: "Bwd Bytes/Bulk Avg", type: "int64" },
  { name: "Bwd Packet/Bulk Avg", type: "int64" },
  { name: "Bwd Bulk Rate Avg", type: "int64" },
  { name: "Subflow Fwd Packets", type: "int64" },
  { name: "Subflow Fwd Bytes", type: "int64" },
  { name: "Subflow Bwd Packets", type: "int64" },
  { name: "Subflow Bwd Bytes", type: "int64" },
  { name: "FWD Init Win Bytes", type: "int64" },
  { name: "Bwd Init Win Bytes", type: "int64" },
  { name: "Fwd Act Data Pkts", type: "int64" },
  { name: "Fwd Seg Size Min", type: "int64" },
  { name: "Active Mean", type: "float64" },
  { name: "Active Std", type: "float64" },
  { name: "Active Max", type: "int64" },
  { name: "Active Min", type: "int64" },
  { name: "Idle Mean", type: "float64" },
  { name: "Idle Std", type: "float64" },
  { name: "Idle Max", type: "int64" },
  { name: "Idle Min", type: "int64" },
  { name: "ICMP Code", type: "int64" },
  { name: "ICMP Type", type: "int64" },
  { name: "Total TCP Flow Time", type: "int64" },
];
