export const columns = [
  { name: "Timestamp", type: "datetime64[ns]" },
  { name: "Src IP", type: "category" },
  { name: "Src Port", type: "int64" },
  { name: "Dst IP", type: "category" },
  { name: "Dst Port", type: "int64" },
  { name: "Protocol", type: "int64" },
  { name: "Flow Duration", type: "int64" },
  { name: "Total Fwd Packet", type: "int64" },
  { name: "Total Bwd packets", type: "int64" },
  { name: "Total Length of Fwd Packet", type: "int64" },
  { name: "Fwd Packet Length Max", type: "int64" },
  { name: "Bwd Packet Length Std", type: "float64" },
  { name: "Flow Bytes/s", type: "float64" },
  { name: "Flow Packets/s", type: "float64" },
  { name: "Bwd IAT Mean", type: "float64" },
  { name: "Flow IAT Min", type: "int64" },
  { name: "Fwd PSH Flags", type: "int64" },
  { name: "Packet Length Mean", type: "float64" },
  { name: "Average Packet Size", type: "float64" },
  { name: "Bwd Init Win Bytes", type: "int64" },
  { name: "Total TCP Flow Time", type: "int64" }
];
